### ISSUE TITLE
Please provide documentation for 2.x API

### ISSUE THREAD

**Issue by tseemann** [phylocanvas/phylocanvas#185]
Richard,

As per https://github.com/phylocanvas/phylocanvas/issues/179 and http://phylocanvas.org/ can you please make some docs for the 2.x API?

You are already at v2.2 ?

This would really help us to deploy Phylocanvas in our apps like Nullarbor.

Thank you,

Torsten

**Comment by andersgs** [comment]
+1

**Comment by richardgoater** [comment]
Hi Torsten, thanks for your interest in the project again.

I will start writing today, beginning with a few markdown files to get it going. It would be really good to know what you're aiming to do so I can cover those areas first. 

We're bumping the minor number whenever we publish new functionality, so .2 just indicates that we've done two more publishes since we turned to 2.0. We will do patch releases for bug fixes and we're not planning on moving the major number any time soon.

I'd love to see the integration when it's done :)

Best,
Richard

**Comment by richardgoater** [comment]
Hi @tseemann, I've added some initial documentation to the wiki of this repo, please take a look and let me know if it helps or not. We'd like to generate the API docs from comments but we're yet to run through the entire codebase, and I'm now looking for a solution that will output a single markdown file.

**Comment by richardgoater** [comment]
Hello again @tseemann, please see an updated http://phylocanvas.org. Method-by-method API documentation is yet to be completed but I hope the new pages help you out a bit.

**Comment by richardgoater** [comment]
Please now also see jsdoc-generated pages under http://phylocanvas.org/docs/api, I'm considering this issue closed!
